=== thjc/httpd-crcsyncproxy/docs/manual/style/modulesynopsis.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY nbsp "&#160;">

<!ENTITY % inlinetags "em | strong | code | a | br | directive | module">

<!ENTITY % blocktags "p | example | note | table | ul | ol | dl | pre
| blockquote">

<!ENTITY % Block "(%blocktags;)*">

<!ENTITY % Inline "(#PCDATA | %inlinetags;)*">

<!ENTITY % BlockOrInline "(#PCDATA | %inlinetags; | %blocktags;)*">

<!ELEMENT modulesynopsis (name , description, status , sourcefile?,
identifier? , compatibility? , summary? , seealso* , section*,
directivesynopsis*)>

<!ELEMENT directivesynopsis (name , description? , syntax? , default?
, contextlist? , override? , modulelist?, status?, compatibility? ,
usage?, seealso*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT status (#PCDATA)>

<!ELEMENT identifier (#PCDATA)>

<!ELEMENT sourcefile (#PCDATA)>

<!ELEMENT compatibility %Inline;>

<!ELEMENT description %Inline;>

<!ELEMENT section (section | title | %blocktags;)*>

<!ATTLIST section id CDATA #IMPLIED>

<!ELEMENT module (#PCDATA)>

<!ELEMENT example (#PCDATA | title | %inlinetags; | %blocktags;)*>

<!ELEMENT seealso %Inline;>

<!ELEMENT a %Inline;>

<!ATTLIST a  href CDATA #IMPLIED 
             name CDATA #IMPLIED>

<!ATTLIST directivesynopsis  type CDATA  #IMPLIED
                             location CDATA  #IMPLIED >

<!ELEMENT syntax %Inline;>

<!ELEMENT default (#PCDATA)>

<!ELEMENT contextlist (context+)+>

<!ELEMENT modulelist (module)+>

<!ELEMENT context (#PCDATA)>

<!ELEMENT override (#PCDATA)>

<!ELEMENT note (#PCDATA | title | %inlinetags; | %blocktags;)*>
<!ATTLIST note type CDATA #IMPLIED>

<!ELEMENT title %Inline;>

<!ELEMENT p %Inline;>

<!ELEMENT ul (li+)>

<!ELEMENT ol (li+)>

<!ELEMENT li %BlockOrInline;>

<!ELEMENT strong %Inline;>

<!ELEMENT br EMPTY>

<!ELEMENT table (tr)+>

<!ELEMENT tr (th | td)+>

<!ELEMENT td %BlockOrInline;>

<!ELEMENT th %BlockOrInline;>

<!ATTLIST td  colspan CDATA  #IMPLIED
                rowspan CDATA  #IMPLIED
                class   CDATA  #IMPLIED >
<!ELEMENT directive (#PCDATA)>

<!ATTLIST directive  module CDATA  #IMPLIED
                     type   CDATA  #IMPLIED >

<!ELEMENT code %Inline;>

<!ELEMENT dl (dd | dt)+>

<!ELEMENT dt %Inline;>

<!ELEMENT dd %BlockOrInline;>

<!ELEMENT em %Inline;>

<!ELEMENT usage %Block;>

<!ELEMENT summary %Block;>

<!ELEMENT blockquote %BlockOrInline;>

<!ELEMENT pre %Inline;>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_slotmem.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision: 559006 $ -->

<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_slotmem.xml.meta">

<name>mod_slotmem</name>
<description>Slot-based memory implementation API.</description>
<status>Extension</status>
<sourcefile>mod_slotmem.c</sourcefile>
<identifier>slotmem_module</identifier>

<summary>
    <p><code>mod_slotmem</code> provides an interface to a
    memory allocation implementation which is based on the
    concept of datasets being in various "slots" within
    a larger memory segment. As such, it is similar in
    concept to a generic table or array. The real use of
    the module is as a front-end to various providers
    (such as <module>mod_sharedmem</module>) which deal
    with the actual implementations. This allows modules
    to use a single API for memory usage, to matter what
    the underlying implementation is.
    </p>

    <p><code>mod_slotmem</code> provides the following
    API functions:
    </p>

    <dl>
      <dt>ap_slotmem_storage_method *ap_slotmem_method(const char *provider)</dt>
      <dd>obtain the provider method desired</dd>

      <dt>apr_status_t ap_slotmem_do(ap_slotmem_storage_method *sm, ap_slotmem_t *s, ap_slotmem_callback_fn_t *func, void *data, apr_pool_t *pool)</dt>
      <dd>call the callback on all worker slots</dd>

      <dt>apr_status_t ap_slotmem_create(ap_slotmem_storage_method *sm, ap_slotmem_t **new, const char *name, apr_size_t item_size, int item_num, apr_pool_t *pool)</dt>
      <dd>create a new slotmem with each item size is item_size.</dd>

      <dt>apr_status_t ap_slotmem_attach(ap_slotmem_storage_method *sm, ap_slotmem_t **new, const char *name, apr_size_t *item_size, int *item_num, apr_pool_t *pool)</dt>
      <dd>attach to an existing slotmem.</dd>

      <dt>apr_status_t ap_slotmem_mem(ap_slotmem_storage_method *sm, ap_slotmem_t *s, int item_id, void**mem)</dt>
      <dd>get the memory associated with this worker slot.</dd>

      <dt>apr_status_t ap_slotmem_lock(ap_slotmem_storage_method *sm, ap_slotmem_t *s)</dt>
      <dd>lock the memory segment</dd>

      <dt>(apr_status_t ap_slotmem_unlock(ap_slotmem_storage_method *sm, ap_slotmem_t *s)</dt>
      <dd>unlock the memory segment</dd>
    </dl>

</summary>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_dumpio.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision: 106803 $ -->

<!--
 Copyright 2002-2004 The Apache Software Foundation

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_dumpio.xml.meta">

<name>mod_dumpio</name>
<description>Dumps to error.log all I/O as desired.</description>
<status>Extension</status>
<sourcefile>mod_dumpio.c</sourcefile>
<identifier>dumpio_module</identifier>

<summary>
    <p><code>mod_dumpio</code> allows for the logging of
    all input received by Apache and/or all output sent by
    Apache to be logged (dumped) to the error.log file.
    </p>

    <p>The data logging is done right after SSL decoding (for
    input) and right before SSL encoding (for output). As can
    be expected, this can produce extreme volumes of data,
    and should only be used when debugging problems.</p>
</summary>

<section id="enable">
    <title>Enabling DumpIO Support</title>

    <p>To enable the module, it should be compiled and
    loaded in to your running Apache configuration. Logging
    can then be enabled or disabled via the below directives.</p>
</section>

<directivesynopsis>

<name>DumpIOInput</name>
<description>Dump all input data to the error log</description>
<syntax>DumpIOInput On|Off</syntax>
<default>DumpIOInput Off</default>
<contextlist><context>server config</context></contextlist>
<compatibility>DumpIOInput is only available in Apache 2.1.3 and 
later.</compatibility>

<name>DumpIOOutput</name>
<description>Dump all output data to the error log</description>
<syntax>DumpIOOutput On|Off</syntax>
<default>DumpIOOutput Off</default>
<contextlist><context>server config</context></contextlist>
<compatibility>DumpIOOutput is only available in Apache 2.1.3 and 
later.</compatibility>

</directivesynopsis>
</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mpm_netware.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.xsl"?>
<modulesynopsis>
<name>mpm_netware</name>
<description>Multi-Processing Module implementing an exclusively threaded web
    server optimized for Novell NetWare</description>
<status>MPM</status>
<sourcefile>mpm_netware.c</sourcefile>
<identifier>mpm_netware_module</identifier>

<summary>
    <p>This Multi-Processing Module (MPM) implements an exclusively threaded web server
    that has been optimized for Novell NetWare.</p>

    <p>The main thread is responsible for launching child
    worker threads which listen for connections and serve them when they
    arrive. Apache always tries to maintain several <em>spare</em>
    or idle worker threads, which stand ready to serve incoming
    requests. In this way, clients do not need to wait for a new
    child threads to be spawned before their requests can be
    served.</p>

    <p>The <code>StartThreads</code>, <code>MinSpareThreads</code>,
    <code>MaxSpareThreads</code>, and <code>MaxThreads</code>
    regulate how the main thread creates worker threads to serve
    requests. In general, Apache is very self-regulating, so most
    sites do not need to adjust these directives from their default
    values. Sites which need to serve more than 250 simultaneous
    requests may need to increase <code>MaxThreads</code>, while
    sites with limited memory may need to decrease
    <code>MaxThreads</code> to keep the server from thrashing (spawning and
    terminating idle threads). More information about
    tuning process creation is provided in the <a
    href="../misc/perf-tuning.html">performance hints</a>
    documentation.</p>

    <p><code>MaxRequestsPerChild</code> controls how frequently the
    server recycles processes by killing old ones and launching new
    ones.&nbsp; On the NetWare OS it is highly recommended that this directive
    remain set to 0.&nbsp; This allows worker threads to continue servicing
    requests indefinitely.</p>

    <p>See also: <a href="../bind.html">Setting which addresses and
    ports Apache uses</a>.</p>
</summary>

<directivesynopsis location="mpm_common"><name>Listen</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ListenBacklog</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MaxRequestsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>SendBufferSize</name>
</directivesynopsis>

<directivesynopsis>
<name>MaxThreads</name>
<syntax>MaxThreads <em>number</em></syntax>
<default>MaxThreads 250</default>
<contextlist><context>server config</context></contextlist>

<usage>
<p>The MaxThreads directive sets the desired maximum
    number worker threads allowable.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>MaxSpareThreads</name>
<syntax>MaxSpareThreads <em>number</em></syntax>
<default>MaxSpareThreads 100</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>The <directive>MaxSpareThreads</directive> directive sets the
    desired maximum number of <em>idle</em> worker threads. An idle
    worker thread is one which is not handling a request. If there are
    more than MaxSpareThreads idle, then the main thread will kill off
    the excess worker threads.</p>

    <p>Tuning of this parameter should only be necessary on very
    busy sites. Setting this parameter to a large number is almost
    always a bad idea.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>MinSpareThreads</name>
<syntax>MinSpareThreads <em>number</em></syntax>
<default>MinSpareThreads 10</default>
<contextlist><context>server config</context></contextlist>

<usage>
<p>The <directive>MinSpareThreads</directive> directive sets the
desired minimum number of <em>idle</em> worker threads. An idle worker
thread is one which is not handling a request. If there are fewer than
MinSpareThreads idle, then the main thread spawns new worker.</p>

    <p>Tuning of this parameter should only be necessary on very
    busy sites. Setting this parameter to a large number is almost
    always a bad idea.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>StartThreads</name>
<syntax>StartThreads <em>number</em></syntax>
<default>StartThreads 50</default>
<contextlist><context>server config</context></contextlist>

<usage>
<p>The StartThreads directive sets the desired
    number of worker threads to spawn and startup</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>ThreadStackSize</name>
<syntax>ThreadStackSize <em>number</em></syntax>
<default>ThreadStackSize 65536</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>This directive tells the server what stack size to use for
    each of the running threads. If you ever get a stack overflow
    you will need to bump this number to a higher setting.</p>
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/apache/docs/manual/mod/mod_plainmem.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision: 559006 $ -->

<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_plainmem.xml.meta">

<name>mod_plainmem</name>
<description>Slot-based shared memory provider.</description>
<status>Extension</status>
<sourcefile>mod_plainmem.c</sourcefile>
<identifier>plainmem_module</identifier>

<summary>
    <p><code>mod_plainmem</code> is a memory provider which
    provides for creation and access to a plain memory segment
    in which the datasets are organized in "slots." Although
    it can be used directly, normally <module>mod_slotmem</module>
    is used as a front-end.
    </p>

    <p>If the memory needs to be shared between threads and
    processes, a better provider would be
    <module>mod_sharedmem</module>.
    </p>

    <p><code>mod_plainmem</code> provides the following
    API functions:
    </p>

    <dl>
      <dt>apr_status_t slotmem_do(ap_slotmem_t *s, ap_slotmem_callback_fn_t *func, void *data, apr_pool_t *pool)</dt>
      <dd>call the callback on all worker slots</dd>

      <dt>apr_status_t slotmem_create(ap_slotmem_t **new, const char *name, apr_size_t item_size, int item_num, apr_pool_t *pool)</dt>
      <dd>create a new slotmem with each item size is item_size.</dd>

      <dt>apr_status_t slotmem_attach(ap_slotmem_t **new, const char *name, apr_size_t *item_size, int *item_num, apr_pool_t *pool)</dt>
      <dd>attach to an existing slotmem.</dd>

      <dt>apr_status_t slotmem_mem(ap_slotmem_t *s, int item_id, void**mem)</dt>
      <dd>get the memory associated with this worker slot.</dd>

      <dt>apr_status_t slotmem_lock(ap_slotmem_t *s)</dt>
      <dd>lock the memory segment</dd>

      <dt>(apr_status_t slotmem_unlock(ap_slotmem_t *s)</dt>
      <dd>unlock the memory segment</dd>
    </dl>

</summary>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_sed.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_sed.xml.meta">

<name>mod_sed</name>
<description>Filtering Input (request) and Output (response) content using sed commands</description>
<status>Experimental</status>
<sourcefile>mod_sed.c sed0.c sed1.c regexp.c regexp.h sed.h</sourcefile>
<identifier>sed_module</identifier>
<compatibility>Available in Apache 2.3 and later</compatibility>

<summary>
<p>
mod_sed is a in-process content filter. mod_sed filter implement the sed edit
commands implemented by Solaris 10 sed
program as described in <a href="http://docs.sun.com/app/docs/doc/816-5165/sed-1b?a=view">man
page</a>. However unlike sed, mod_sed doesn't take data from
standard
input. Instead filter act on the entity data sent between client and
server. mod_sed can be used as a input or output filter. mod_sed is a
content filter which means that it can not be used to modify client or
server http headers.
</p>
<p>
mod_sed output filter accept a chunk of data and execute the sed scripts on data and generates the output which is passed to next filter in the filter chain.
</p>

<p>
mod_sed input filter reads the data from next filter in filter chain and executes the sed scripts and returns the generated data to caller filter in the filter chain.
</p>

<p>
Both input and output filter only process the data if new line character is seen in the content. At the end of the data, rest of the data is treated as last line.
</p>

<p>A tutorial article on mod_sed, and why it is more powerful than simple
string or regular expression search and replace, is available in <a
href="http://blogs.sun.com/basant/entry/using_mod_sed_to_filter">on
the author's blog</a>.</p>

</summary>

<directivesynopsis>
<name>OutputSed</name>
<description>Sed command for filter the response content</description>
<syntax>OutputSed <var>sed-command</var></syntax>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>

<usage>
    <p>The <directive>OutputSed</directive> directive specify the sed
    command which will be executed on the response.
    </p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>InputSed</name>
<description>Sed command to filter the request data (typically post data)</description>
<syntax>InputSed <var>sed-command</var></syntax>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>

<usage>
    <p>The <directive>InputSed</directive> directive specify the sed command
    which will be executed on the request data e.g POST data.
    </p>
</usage>
</directivesynopsis>

<section id="sampleconf"><title>Sample Configuration</title>
    <example><title>Adding a output filter </title>
         # In following example, sed filter will replace the string <br />
         # "monday" to "MON" and the string "sunday" to SUN in html document <br />
         # before sending to client. <br />
        <indent>
        &lt;Directory "/var/www/docs/sed"&gt; <br />
           <indent>
           AddOutputFilter Sed html <br />
           OutputSed "s/monday/MON/g" <br />
           OutputSed "s/sunday/SUN/g" <br />
           </indent>
        &lt;/Directory&gt; <br />
        </indent>
    </example>

    <example><title>Adding a input filter </title>
         # In following example, sed filter will replace the string <br />
         # "monday" to "MON" and the string "sunday" to SUN in the POST data <br />
         # sent to php <br />
        <indent>
        &lt;Directory "/var/www/docs/sed"&gt; <br />
           <indent>
           AddInputFilter Sed php <br />
           OutputSed "s/monday/MON/g" <br />
           OutputSed "s/sunday/SUN/g" <br />
           </indent>
        &lt;/Directory&gt; <br />
        </indent>
    </example>
</section>
<section id="sed_commands"><title>Sed Commands</title>
    <p>
    Complete details of the sed command can be found from
   <a href="http://docs.sun.com/app/docs/doc/816-5165/sed-1b?a=view">sed man
page</a>.
    </p>
    <dl>
        <dt><code>b</code></dt>
        <dd>branch to the label specified (Similar to goto)</dd>
        <dt><code>h</code></dt>
        <dd>Copy the current line to hold buffer.</dd>
        <dt><code>H</code></dt>
        <dd>Append the current line to hold buffer.</dd>
        <dt><code>g</code></dt>
        <dd>Copy the hold buffer into the current line</dd>
        <dt><code>G</code></dt>
        <dd>Append the hold buffer into the current line</dd>
        <dt><code>x</code></dt>
        <dd>Swap the content of hold buffer and current line</dd>
    </dl>
</section>
</modulesynopsis>
