=== thjc/httpd-crcsyncproxy/docs/manual/style/modulesynopsis.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY nbsp "&#160;">

<!ENTITY % inlinetags "em | strong | code | a | br | directive | module">

<!ENTITY % blocktags "p | example | note | table | ul | ol | dl | pre
| blockquote">

<!ENTITY % Block "(%blocktags;)*">

<!ENTITY % Inline "(#PCDATA | %inlinetags;)*">

<!ENTITY % BlockOrInline "(#PCDATA | %inlinetags; | %blocktags;)*">

<!ELEMENT modulesynopsis (name , description, status , sourcefile?,
identifier? , compatibility? , summary? , seealso* , section*,
directivesynopsis*)>

<!ELEMENT directivesynopsis (name , description? , syntax? , default?
, contextlist? , override? , modulelist?, status?, compatibility? ,
usage?, seealso*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT status (#PCDATA)>

<!ELEMENT identifier (#PCDATA)>

<!ELEMENT sourcefile (#PCDATA)>

<!ELEMENT compatibility %Inline;>

<!ELEMENT description %Inline;>

<!ELEMENT section (section | title | %blocktags;)*>

<!ATTLIST section id CDATA #IMPLIED>

<!ELEMENT module (#PCDATA)>

<!ELEMENT example (#PCDATA | title | %inlinetags; | %blocktags;)*>

<!ELEMENT seealso %Inline;>

<!ELEMENT a %Inline;>

<!ATTLIST a  href CDATA #IMPLIED 
             name CDATA #IMPLIED>

<!ATTLIST directivesynopsis  type CDATA  #IMPLIED
                             location CDATA  #IMPLIED >

<!ELEMENT syntax %Inline;>

<!ELEMENT default (#PCDATA)>

<!ELEMENT contextlist (context+)+>

<!ELEMENT modulelist (module)+>

<!ELEMENT context (#PCDATA)>

<!ELEMENT override (#PCDATA)>

<!ELEMENT note (#PCDATA | title | %inlinetags; | %blocktags;)*>
<!ATTLIST note type CDATA #IMPLIED>

<!ELEMENT title %Inline;>

<!ELEMENT p %Inline;>

<!ELEMENT ul (li+)>

<!ELEMENT ol (li+)>

<!ELEMENT li %BlockOrInline;>

<!ELEMENT strong %Inline;>

<!ELEMENT br EMPTY>

<!ELEMENT table (tr)+>

<!ELEMENT tr (th | td)+>

<!ELEMENT td %BlockOrInline;>

<!ELEMENT th %BlockOrInline;>

<!ATTLIST td  colspan CDATA  #IMPLIED
                rowspan CDATA  #IMPLIED
                class   CDATA  #IMPLIED >
<!ELEMENT directive (#PCDATA)>

<!ATTLIST directive  module CDATA  #IMPLIED
                     type   CDATA  #IMPLIED >

<!ELEMENT code %Inline;>

<!ELEMENT dl (dd | dt)+>

<!ELEMENT dt %Inline;>

<!ELEMENT dd %BlockOrInline;>

<!ELEMENT em %Inline;>

<!ELEMENT usage %Block;>

<!ELEMENT summary %Block;>

<!ELEMENT blockquote %BlockOrInline;>

<!ELEMENT pre %Inline;>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_authz_groupfile.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis>

<name>mod_authz_groupfile</name>
<description>Group authorization using plaintext files</description>
<status>Extension</status>
<sourcefile>mod_authz_groupfile.c</sourcefile>
<identifier>authz_groupfile_module</identifier>
<compatibility>Available in Apache 2.0.42 and later</compatibility>

<summary>
    <p>This module provides authorization capabilities so that
       authenticated users can be allowed or denied access to portions
       of the web site by group membership. Similar functionality is
       provided by <module>mod_authz_dbm</module>.</p>
</summary>

<seealso><directive module="core">Require</directive></seealso>
<seealso><directive module="core">Satisfy</directive></seealso>

<directivesynopsis>
<name>AuthGroupFile</name>
<description>Sets the name of a text file containing the list
of user groups for authentication</description>
<syntax>AuthGroupFile <em>file-path</em></syntax>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>The <directive>AuthGroupFile</directive> directive sets the
    name of a textual file containing the list of user groups for user
    authentication.  <em>File-path</em> is the path to the group
    file. If it is not absolute (<em>i.e.</em>, if it doesn't begin
    with a slash), it is treated as relative to the <directive
    module="core">ServerRoot</directive>.</p>

    <p>Each line of the group file contains a groupname followed by a
    colon, followed by the member usernames separated by spaces.
    Example:</p> 

    <example>mygroup: bob joe anne</example> 

    <p>Note that searching large text files is <em>very</em>
    inefficient; <directive
    module="mod_authz_dbm">AuthDBMGroupFile</directive> should be used
    instead.</p>

    <note><title>Security</title>
    <p>Make sure that the <directive>AuthGroupFile</directive> is
	stored outside the document tree of the web-server; do <em>not</em>
	put it in the directory that it protects. Otherwise, clients will
	be able to download the <directive>AuthGroupFile</directive>.</p>
    </note>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthzGroupFileAuthoritative</name>
<description>Sets whether authorization will be passed on to lower level modules</description>
<syntax>AuthzGroupFileAuthoritative on|off</syntax>
<default>AuthzGroupFileAuthoritative on</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>

    <p>Setting the <directive>AuthzGroupFileAuthoritative</directive>
    directive explicitly to <strong>'off'</strong> allows for
    authorization to be passed on to lower level modules (as defined in
    the <code>Configuration</code> and <code>modules.c</code> file if
    there is <strong>no userID</strong> or <strong>rule</strong> matching
    the supplied userID. If there is a userID and/or rule specified; the
    usual password and access checks will be applied and a failure will
    give an Authorization Required reply.</p>

    <p>So if a valid <directive module="core">Require</directive>
    directive applies to more than one module; then the first module
    will verify the credentials; and no access is passed on;
    regardless of the <directive>AuthzGroupFileAuthoritative</directive>
    setting.</p>

    <p>By default, control is not passed on and an unknown userID
    or rule will result in an Authorization Required reply. Not
    setting it thus keeps the system secure and forces an NCSA
    compliant behaviour.</p>

    <p>Security: Do consider the implications of allowing a user to
    allow fall-through in his .htaccess file; and verify that this
    is really what you want; Generally it is easier to just secure
    a single .htpasswd file, than it is to secure a database which
    might have more access interfaces.</p>
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/apache/docs/manual/mod/mod_heartmonitor.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision$ -->

<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_heartmonitor.xml.meta">

<name>mod_heartmonitor</name>
<description></description>
<status>Extension</status>
<sourcefile>mod_heartmonitor.c</sourcefile>
<identifier>heartmonitor_module</identifier>
<compatibility>Available in 2.3 and later</compatibility>

<summary>
    <note><!-- FIXME: -->This document is still under development.</note>
</summary>

<directivesynopsis>
<name>HeartbeatListen</name>
<description>Address to listen for heartbeat requests</description>
<syntax></syntax>
<contextlist><context>server config</context></contextlist>

<usage>
    <note><!-- FIXME: -->This document is still under development.</note>
</usage> 
</directivesynopsis>

<directivesynopsis>
<name>HeartbeatStorage</name>
<description>Path to store heartbeat data</description>
<syntax>HeartbeatStorage <var>file-path</var></syntax>
<default>HeartbeatStorage logs/hb.dat</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <note><!-- FIXME: -->This document is still under development.</note>
</usage> 
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_authn_dbm.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis>

<name>mod_authn_dbm</name>
<description>User authentication using DBM files</description>
<status>Extension</status>
<sourcefile>mod_authn_dbm.c</sourcefile>
<identifier>authn_dbm_module</identifier>
<compatibility>Available in Apache 2.0.42 and later</compatibility>

<summary>
    <p>This module provides authentication front-ends such as
    <module>mod_auth_digest</module> and <module>mod_auth_basic</module>
    to authenticate users by looking up users in plain text password files.
    Similar functionality is provided by <module>mod_authn_file</module>.</p>

    <p>When using <module>mod_auth_basic</module> or
    <module>mod_auth_digest</module>, this module is invoked via the
    <directive module="mod_auth_basic">AuthBasicProvider</directive> or
    <directive module="mod_auth_digest">AuthDigestProvider</directive>
    with the 'dbm' value.</p>
</summary>

<seealso><directive module="core">AuthName</directive></seealso>
<seealso><directive module="core">AuthType</directive></seealso>
<seealso>
  <directive module="mod_auth_basic">AuthBasicProvider</directive>
</seealso>
<seealso>
  <directive module="mod_auth_digest">AuthDigestProvider</directive>
</seealso>

<directivesynopsis>
<name>AuthDBMUserFile</name>
<description>Sets the name of a database file containing the list of users and
passwords for authentication</description>
<syntax>AuthDBMUserFile <em>file-path</em></syntax>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>The <directive>AuthDBMUserFile</directive> directive sets the
    name of a DBM file containing the list of users and passwords for
    user authentication. <em>File-path</em> is the absolute path to
    the user file.</p>

    <p>The user file is keyed on the username. The value for a user is
    the <code>crypt()</code> encrypted password, optionally followed
    by a colon and arbitrary data. The colon and the data following it
    will be ignored by the server.</p>

    <p>Security: make sure that the
    <directive>AuthDBMUserFile</directive> is stored outside the
    document tree of the web-server; do <em>not</em> put it in the
    directory that it protects. Otherwise, clients will be able to
    download the <directive>AuthDBMUserFile</directive>.</p>

    <p>Important compatibility note: The implementation of
    "dbmopen" in the apache modules reads the string length of the
    hashed values from the DBM data structures, rather than relying
    upon the string being NULL-appended. Some applications, such as
    the Netscape web server, rely upon the string being
    NULL-appended, so if you are having trouble using DBM files
    interchangeably between applications this may be a part of the
    problem.</p>

    <p>A perl script called
    <a href="../programs/dbmmanage.html">dbmmanage</a> is included with
    Apache. This program can be used to create and update DBM
    format password files for use with this module.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthDBMType</name>
<description>Sets the type of database file that is used to
store passwords</description>
<syntax>AuthDBMType default|SDBM|GDBM|NDBM|DB</syntax>
<default>AuthDBMType default</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>
<compatibility>Available in version 2.0.30 and later.</compatibility>

<usage>

<p>Sets the type of database file that is used to store the passwords.
The default database type is determined at compile time.  The
availability of other types of database files also depends on
<a href="../install.html#dbm">compile-time settings</a>.</p>

<p>It is crucial that whatever program you use to create your password
files is configured to use the same type of database.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthDBMAuthoritative</name>
<description>Sets whether authentication and authorization will be
passwed on to lower level modules</description>
<syntax>AuthDBMAuthoritative on|off</syntax>
<default>AuthDBMAuthoritative on</default>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>

    <p>Setting the <directive>AuthDBMAuthoritative</directive>
    directive explicitly to <strong>'off'</strong> allows for both
    authentication and authorization to be passed on to lower level
    modules (as defined in the <code>Configuration</code> and
    <code>modules.c</code> file if there is <strong>no userID</strong>
    or <strong>rule</strong> matching the supplied userID. If there is
    a userID and/or rule specified; the usual password and access
    checks will be applied and a failure will give an Authorization
    Required reply.</p>

    <p>So if a userID appears in the database of more than one module;
    or if a valid <directive module="core">Require</directive>
    directive applies to more than one module; then the first module
    will verify the credentials; and no access is passed on;
    regardless of the <directive>AuthAuthoritative</directive> setting.</p>

    <p>A common use for this is in conjunction with one of the
    auth providers; such as <module>mod_authn_file</module>. Whereas this
    DBM module supplies the bulk of the user credential checking; a
    few (administrator) related accesses fall through to a lower
    level with a well protected .htpasswd file.</p>

    <p>By default, control is not passed on and an unknown userID
    or rule will result in an Authorization Required reply. Not
    setting it thus keeps the system secure and forces an NCSA
    compliant behaviour.</p>

    <p>Security: Do consider the implications of allowing a user to
    allow fall-through in his .htaccess file; and verify that this
    is really what you want; Generally it is easier to just secure
    a single .htpasswd file, than it is to secure a database which
    might have more access interfaces.</p>
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/worker.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.xsl"?>
<modulesynopsis>
<name>worker</name>
<description>Multi-Processing Module implementing a hybrid
    multi-threaded multi-process web server</description>
<status>MPM</status>
<sourcefile>worker.c</sourcefile>
<identifier>mpm_worker_module</identifier>

<summary>
    <p>This Multi-Processing Module (MPM) implements a hybrid
    multi-process multi-threaded server. Each process has a fixed
    number of threads. The server adjusts to handle load by
    increasing or decreasing the number of processes.</p>

    <p>A single control process is responsible for launching child
    processes. Each child process creates a fixed number of threads
    as specified in the <code>ThreadsPerChild</code> directive. The
    individual threads then listen for connections and serve them
    when they arrive.</p>

    <p>Apache always tries to maintain a pool of <em>spare</em> or
    idle server threads, which stand ready to serve incoming
    requests. In this way, clients do not need to wait for a new
    threads or processes to be created before their requests can be
    served. Apache assesses the total number of idle threads in all
    processes, and forks or kills processes to keep this number
    within the boundaries specified by <code>MinSpareThreads</code>
    and <code>MaxSpareThreads</code>. Since this process is very
    self-regulating, it is rarely necessary to modify these
    directives from their default values. The maximum number of
    clients that may be served simultaneously is determined by
    multiplying the maximum number of server processes that will be
    created (<code>MaxClients</code>) by the number of threads
    created in each process (<code>ThreadsPerChild</code>).</p>

    <p>While the parent process is usually started as root under
    Unix in order to bind to port 80, the child processes and
    threads are launched by Apache as a less-privileged user. The
    <code>User</code> and <code>Group</code> directives are used to
    set the privileges of the Apache child processes. The child
    processes must be able to read all the content that will be
    served, but should have as few privileges beyond that as
    possible. In addition, unless <a
    href="../suexec.html">suexec</a> is used, these directives also
    set the privileges which will be inherited by CGI scripts.</p>

    <p><code>MaxRequestsPerChild</code> controls how frequently the
    server recycles processes by killing old ones and launching new
    ones.</p>

    <p>See also: <a href="../bind.html">Setting which addresses and
    ports Apache uses</a>.</p>
</summary>

<directivesynopsis location="mpm_common"><name>CoreDumpDirectory</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>Group</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>PidFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>Listen</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ListenBacklog</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>LockFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MaxClients</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MaxRequestsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MaxSpareThreads</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>MinSpareThreads</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ScoreBoardFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>SendBufferSize</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ServerLimit</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>StartServers</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ThreadLimit</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>ThreadsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common"><name>User</name>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/apache/docs/manual/mod/mod_lbmethod_heartbeat.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision$ -->

<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_lbmethod_heartbeat.xml.meta">

<name>mod_lbmethod_heartbeat</name>
<description><!-- FIXME: --> This document is still under development.</description>
<status>Extension</status>
<sourcefile>mod_lbmethod_heartbeat.c</sourcefile>
<identifier>lbmethod_heartbeat_module</identifier>
<compatibility>Available in version 2.3 and later</compatibility>

<summary>
    <note><!-- FIXME: --> This document is still under development.</note>
</summary>
<seealso><module>mod_proxy</module></seealso>
<seealso><module>mod_proxy_balancer</module></seealso>
<seealso><module>mod_heartbeat</module></seealso>
<seealso><module>mod_heartmonitor</module></seealso>

<directivesynopsis>
<name>HeartbeatStorage</name>
<description>Path to read heartbeat data</description>
<syntax>HeartbeatStorage <var>file-path</var></syntax>
<default>HeartbeatStorage logs/hb.dat</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <note><!-- FIXME: -->This document is still under development.</note>
</usage> 
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_auth_basic.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis>

<name>mod_auth_basic</name>
<description>Basic authentication</description>
<status>Base</status>
<sourcefile>mod_auth_basic.c</sourcefile>
<identifier>auth_basic_module</identifier>
<compatibility>Available in Apache 2.0.44 and later</compatibility>

<summary>

    <p>This module allows the use of HTTP Basic Authentication to
    restrict access by looking up users in the given providers.
    HTTP Digest Authentication is provided by
    <module>mod_auth_digest</module>.</p>

</summary>
<seealso><directive module="core">AuthName</directive></seealso>
<seealso><directive module="core">AuthType</directive></seealso>

<directivesynopsis>
<name>AuthBasicProvider</name>
<description>Sets the authentication provider(s) for this location</description>
<syntax>AuthBasicProvider <em>provider-name</em></syntax>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>The <directive>AuthBasicProvider</directive> directive sets 
    which provider is used to authenticate the users for this location.</p>

    <p>See <module>mod_authn_dbm</module>, <module>mod_authn_file</module>
    for providers.</p>

</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthBasicAuthoritative</name>
<description>Sets whether authorization and authentication are
passed to lower level modules</description>
<syntax>AuthBasicAuthoritative on|off</syntax>
<default>AuthBasicAuthoritative on</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>Setting the <directive>AuthBasicAuthoritative</directive> directive
    explicitly to <strong>'off'</strong> allows for both
    authentication and authorization to be passed on to lower level
    modules (as defined in the <code>Configuration</code> and
    <code>modules.c</code> files) if there is <strong>no
    userID</strong> or <strong>rule</strong> matching the supplied
    userID. If there is a userID and/or rule specified; the usual
    password and access checks will be applied and a failure will give
    an Authorization Required reply.</p>

    <p>So if a userID appears in the database of more than one module;
    or if a valid <directive module="core">Require</directive>
    directive applies to more than one module; then the first module
    will verify the credentials; and no access is passed on;
    regardless of the AuthAuthoritative setting.</p>

    <p>By default; control is not passed on; and an unknown userID or
    rule will result in an Authorization Required reply. Not setting
    it thus keeps the system secure; and forces an NCSA compliant
    behaviour.</p>

</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_authn_core.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<!-- $LastChangedRevision$ -->

<!--
 Copyright 2002-2005 The Apache Software Foundation or its licensors, as
 applicable.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<modulesynopsis metafile="mod_authn_core.xml.meta">

<name>mod_authn_core</name> 
<description>Core Authentication</description>
<status>Base</status>
<sourcefile>mod_authn_core.c</sourcefile>
<identifier>authn_core_module</identifier>
<compatibility>Available in Apache 2.3 and later</compatibility>

<summary>
    <p>This module provides core authentication capabilities to 
    allow or deny access to portions of the web site. 
    <module>mod_authn_core</module> provides directives that are 
    common to all authentication providers.</p>
</summary>

<directivesynopsis>
<name>AuthName</name>
<description>Authorization realm for use in HTTP
authentication</description>
<syntax>AuthName <var>auth-domain</var></syntax>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>This directive sets the name of the authorization realm for a
    directory. This realm is given to the client so that the user
    knows which username and password to send.
    <directive>AuthName</directive> takes a single argument; if the
    realm name contains spaces, it must be enclosed in quotation
    marks.  It must be accompanied by <directive
    module="mod_authn_core">AuthType</directive> and <directive
    module="mod_authz_core">Require</directive> directives, and directives such
    as <directive module="mod_authn_file">AuthUserFile</directive> and
    <directive module="mod_authz_groupfile">AuthGroupFile</directive> to
    work.</p>

   <p>For example:</p>

   <example>
     AuthName "Top Secret"
   </example>

    <p>The string provided for the <code>AuthName</code> is what will
    appear in the password dialog provided by most browsers.</p>
</usage>
<seealso><a
    href="../howto/auth.html">Authentication, Authorization, and
    Access Control</a></seealso>
</directivesynopsis>

<directivesynopsis>
<name>AuthType</name>
<description>Type of user authentication</description>
<syntax>AuthType Basic|Digest</syntax>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>This directive selects the type of user authentication for a
    directory. The authentication types available are
    <code>Basic</code> (implemented by
    <module>mod_auth_basic</module>) and <code>Digest</code>
    (implemented by <module>mod_auth_digest</module>).</p>

    <p>To implement authentication, you must also use the <directive
    module="mod_authn_core">AuthName</directive> and <directive
    module="mod_authz_core">Require</directive> directives.  In addition, the
    server must have an authentication-provider module such as
    <module>mod_authn_file</module> and an authorization module such
    as <module>mod_authz_user</module>.</p>
</usage> 

<seealso><a href="../howto/auth.html">Authentication, Authorization,
    and Access Control</a></seealso> 
</directivesynopsis>


</modulesynopsis>
