=== thjc/httpd-crcsyncproxy/docs/manual/style/modulesynopsis.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY nbsp "&#160;">

<!ENTITY % inlinetags "em | strong | code | a | br | directive | module">

<!ENTITY % blocktags "p | example | note | table | ul | ol | dl | pre
| blockquote">

<!ENTITY % Block "(%blocktags;)*">

<!ENTITY % Inline "(#PCDATA | %inlinetags;)*">

<!ENTITY % BlockOrInline "(#PCDATA | %inlinetags; | %blocktags;)*">

<!ELEMENT modulesynopsis (name , description, status , sourcefile?,
identifier? , compatibility? , summary? , seealso* , section*,
directivesynopsis*)>

<!ELEMENT directivesynopsis (name , description? , syntax? , default?
, contextlist? , override? , modulelist?, status?, compatibility? ,
usage?, seealso*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT status (#PCDATA)>

<!ELEMENT identifier (#PCDATA)>

<!ELEMENT sourcefile (#PCDATA)>

<!ELEMENT compatibility %Inline;>

<!ELEMENT description %Inline;>

<!ELEMENT section (section | title | %blocktags;)*>

<!ATTLIST section id CDATA #IMPLIED>

<!ELEMENT module (#PCDATA)>

<!ELEMENT example (#PCDATA | title | %inlinetags; | %blocktags;)*>

<!ELEMENT seealso %Inline;>

<!ELEMENT a %Inline;>

<!ATTLIST a  href CDATA #IMPLIED 
             name CDATA #IMPLIED>

<!ATTLIST directivesynopsis  type CDATA  #IMPLIED
                             location CDATA  #IMPLIED >

<!ELEMENT syntax %Inline;>

<!ELEMENT default (#PCDATA)>

<!ELEMENT contextlist (context+)+>

<!ELEMENT modulelist (module)+>

<!ELEMENT context (#PCDATA)>

<!ELEMENT override (#PCDATA)>

<!ELEMENT note (#PCDATA | title | %inlinetags; | %blocktags;)*>
<!ATTLIST note type CDATA #IMPLIED>

<!ELEMENT title %Inline;>

<!ELEMENT p %Inline;>

<!ELEMENT ul (li+)>

<!ELEMENT ol (li+)>

<!ELEMENT li %BlockOrInline;>

<!ELEMENT strong %Inline;>

<!ELEMENT br EMPTY>

<!ELEMENT table (tr)+>

<!ELEMENT tr (th | td)+>

<!ELEMENT td %BlockOrInline;>

<!ELEMENT th %BlockOrInline;>

<!ATTLIST td  colspan CDATA  #IMPLIED
                rowspan CDATA  #IMPLIED
                class   CDATA  #IMPLIED >
<!ELEMENT directive (#PCDATA)>

<!ATTLIST directive  module CDATA  #IMPLIED
                     type   CDATA  #IMPLIED >

<!ELEMENT code %Inline;>

<!ELEMENT dl (dd | dt)+>

<!ELEMENT dt %Inline;>

<!ELEMENT dd %BlockOrInline;>

<!ELEMENT em %Inline;>

<!ELEMENT usage %Block;>

<!ELEMENT summary %Block;>

<!ELEMENT blockquote %BlockOrInline;>

<!ELEMENT pre %Inline;>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_authz_dbm.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis>

<name>mod_authz_dbm</name>
<description>Group authorization using DBM files</description>
<status>Extension</status>
<sourcefile>mod_authz_dbm.c</sourcefile>
<identifier>authz_dbm_module</identifier>
<compatibility>Available in Apache 2.1 and later</compatibility>

<summary>
    <p>This module provides authorization capabilities so that
       authenticated users can be allowed or denied access to portions
       of the web site by group membership. Similar functionality is
       provided by <module>mod_authz_groupfile</module>.</p>
</summary>

<seealso><directive module="core">Require</directive></seealso>
<seealso><directive module="core">Satisfy</directive></seealso>

<directivesynopsis>
<name>AuthDBMGroupFile</name>
<description>Sets the name of the database file containing the list
of user groups for authentication</description>
<syntax>AuthDBMGroupFile <em>file-path</em></syntax>
<contextlist><context>directory</context><context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>The <directive>AuthDBMGroupFile</directive> directive sets the
    name of a DBM file containing the list of user groups for user
    authentication.  <em>File-path</em> is the absolute path to the
    group file.</p>

    <p>The group file is keyed on the username. The value for a
    user is a comma-separated list of the groups to which the users
    belongs. There must be no whitespace within the value, and it
    must never contain any colons.</p>

    <p>Security: make sure that the
    <directive>AuthDBMGroupFile</directive> is stored outside the
    document tree of the web-server; do <em>not</em> put it in the
    directory that it protects. Otherwise, clients will be able to
    download the <directive>AuthDBMGroupFile</directive> unless
    otherwise protected.</p>

    <p>Combining Group and Password DBM files: In some cases it is
    easier to manage a single database which contains both the
    password and group details for each user. This simplifies any
    support programs that need to be written: they now only have to
    deal with writing to and locking a single DBM file. This can be
    accomplished by first setting the group and password files to
    point to the same DBM:</p>

<example>
AuthDBMGroupFile /www/userbase<br />
AuthDBMUserFile /www/userbase
</example>

    <p>The key for the single DBM is the username. The value consists
    of</p>

<example>Unix Crypt-ed Password : List of Groups [ : (ignored)
      ]</example>

    <p>The password section contains the Unix <code>crypt()</code>
    password as before. This is followed by a colon and the comma
    separated list of groups. Other data may optionally be left in the
    DBM file after another colon; it is ignored by the authentication
    module. This is what www.telescope.org uses for its combined
    password and group database.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthzDBMType</name>
<description>Sets the type of database file that is used to
store passwords</description>
<syntax>AuthzDBMType default|SDBM|GDBM|NDBM|DB</syntax>
<default>AuthzDBMType default</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>
<compatibility>Available in version 2.0.30 and later.</compatibility>

<usage>

<p>Sets the type of database file that is used to store the passwords.
The default database type is determined at compile time.  The
availability of other types of database files also depends on
<a href="../install.html#dbm">compile-time settings</a>.</p>

<p>It is crucial that whatever program you use to create your password
files is configured to use the same type of database.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthzDBMAuthoritative</name>
<description>Sets whether authorization will be passed on to lower level modules</description>
<syntax>AuthzDBMAuthoritative on|off</syntax>
<default>AuthzDBMAuthoritative on</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>

    <p>Setting the <directive>AuthzDBMAuthoritative</directive>
    directive explicitly to <strong>'off'</strong> allows for both
    authentication and authorization to be passed on to lower level
    modules (as defined in the <code>Configuration</code> and
    <code>modules.c</code> file if there is <strong>no userID</strong>
    or <strong>rule</strong> matching the supplied userID. If there is
    a userID and/or rule specified; the usual password and access
    checks will be applied and a failure will give an Authorization
    Required reply.</p>

    <p>So if a userID appears in the database of more than one module;
    or if a valid <directive module="core">Require</directive>
    directive applies to more than one module; then the first module
    will verify the credentials; and no access is passed on;
    regardless of the <directive>AuthAuthoritative</directive> setting.</p>

    <p>A common use for this is in conjunction with one of the
    auth providers; such as <module>mod_authn_file</module>. Whereas this
    DBM module supplies the bulk of the user credential checking; a
    few (administrator) related accesses fall through to a lower
    level with a well protected .htpasswd file.</p>

    <p>By default, control is not passed on and an unknown userID
    or rule will result in an Authorization Required reply. Not
    setting it thus keeps the system secure and forces an NCSA
    compliant behaviour.</p>

    <p>Security: Do consider the implications of allowing a user to
    allow fall-through in his .htaccess file; and verify that this
    is really what you want; Generally it is easier to just secure
    a single .htpasswd file, than it is to secure a database which
    might have more access interfaces.</p>
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/mod_authn_file.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.en.xsl"?>
<modulesynopsis>

<name>mod_authn_file</name>
<description>User authentication using text files</description>
<status>Base</status>
<sourcefile>mod_authn_file.c</sourcefile>
<identifier>authn_file_module</identifier>
<compatibility>Available in Apache 2.0.42 and later</compatibility>

<summary>

    <p>This module provides authentication front-ends such as
    <module>mod_auth_digest</module> and <module>mod_auth_basic</module>
    to authenticate users by looking up users in plain text password files.
    Similar functionality is provided by <module>mod_authn_dbm</module>.</p>

    <p>When using <module>mod_auth_basic</module> or
    <module>mod_auth_digest</module>, this module is invoked via the
    <directive module="mod_auth_basic">AuthBasicProvider</directive> or
    <directive module="mod_auth_digest">AuthDigestProvider</directive>
    with the 'file' value.</p>

</summary>
<seealso><directive module="core">AuthName</directive></seealso>
<seealso><directive module="core">AuthType</directive></seealso>
<seealso>
  <directive module="mod_auth_basic">AuthBasicProvider</directive>
</seealso>
<seealso>
  <directive module="mod_auth_digest">AuthDigestProvider</directive>
</seealso>
 
<directivesynopsis>
<name>AuthUserFile</name>
<description>Sets the name of a text file containing the list of users and
passwords for authentication</description>
<syntax>AuthUserFile <em>file-path</em></syntax>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <p>The <directive>AuthUserFile</directive> directive sets the name
    of a textual file containing the list of users and passwords for
    user authentication. <em>File-path</em> is the path to the user
    file. If it is not absolute (<em>i.e.</em>, if it doesn't begin
    with a slash), it is treated as relative to the <directive
    module="core">ServerRoot</directive>.</p>

    <p>Each line of the user file contains a username followed by
    a colon, followed by the <code>crypt()</code> encrypted
    password. The behavior of multiple occurrences of the same user is
    undefined.</p>

    <p>The utility <a href="../programs/htpasswd.html">htpasswd</a>
    which is installed as part of the binary distribution, or which
    can be found in <code>src/support</code>, is used to maintain
    this password file. See the <code>man</code> page for more
    details. In short:</p>

    <p>Create a password file 'Filename' with 'username' as the
    initial ID. It will prompt for the password:</p>
    <example>htpasswd -c Filename username</example>

    <p>Add or modify 'username2' in the password file 'Filename':</p>
    <example>htpasswd Filename username2</example>

    <p>Note that searching large text files is <em>very</em>
    inefficient; <directive
    module="mod_authn_dbm">AuthDBMUserFile</directive> should be used
    instead.</p>

    <note><title>Security</title>
    <p>Make sure that the <directive>AuthUserFile</directive> is
	stored outside the document tree of the web-server; do <em>not</em>
	put it in the directory that it protects. Otherwise, clients will
	be able to download the <directive>AuthUserFile</directive>.</p>
    </note>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>AuthUserFileAuthoritative</name>
<description>Sets whether authorization and authentication are
passed to lower level modules</description>
<syntax>AuthUserFileAuthoritative on|off</syntax>
<default>AuthUserFileAuthoritative on</default>
<contextlist>
  <context>directory</context>
  <context>.htaccess</context>
</contextlist>
<override>AuthConfig</override>

<usage>
    <note>This information has not been updated for Apache 2.0, which
    uses a different system for module ordering.</note>

    <p>Setting the <directive>AuthAuthoritative</directive> directive
    explicitly to <strong>'off'</strong> allows for both
    authentication and authorization to be passed on to lower level
    modules (as defined in the <code>Configuration</code> and
    <code>modules.c</code> files) if there is <strong>no
    userID</strong> or <strong>rule</strong> matching the supplied
    userID. If there is a userID and/or rule specified; the usual
    password and access checks will be applied and a failure will give
    an Authorization Required reply.</p>

    <p>So if a userID appears in the database of more than one module;
    or if a valid <directive module="core">Require</directive>
    directive applies to more than one module; then the first module
    will verify the credentials; and no access is passed on;
    regardless of the AuthAuthoritative setting.</p>

    <p>By default; control is not passed on; and an unknown userID or
    rule will result in an Authorization Required reply. Not setting
    it thus keeps the system secure; and forces an NCSA compliant
    behaviour.</p>

    <note><title>Security</title> Do consider the implications of
    allowing a user to allow fall-through in his .htaccess file; and
    verify that this is really what you want; Generally it is easier
    to just secure a single .htpasswd file, than it is to secure a
    database such as mSQL. Make sure that the <directive
    module="mod_authn_file">AuthUserFile</directive> and the <directive
    module="mod_authz_groupfile">AuthGroupFile</directive> are stored outside
    the document tree of the web-server; do <em>not</em> put them in the
    directory that they protect. Otherwise, clients will be able to
    download the <directive module="mod_authn_file">AuthUserFile</directive>
    and the <directive module="mod_authz_groupfile">AuthGroupFile</directive>.
    </note>
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/perchild.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.xsl"?>
<modulesynopsis>

<name>perchild</name>
<description>Multi-Processing Module allowing for daemon processes
    serving requests to be assigned a variety of different
    userids</description>
<status>MPM</status>
<sourcefile>perchild.c</sourcefile>
<identifier>mpm_perchild_module</identifier>

<summary>
<note type="warning">
This MPM does not currently work on most platforms.  Work is ongoing to
make it functional.
</note>

    <p>This Multi-Processing Module (MPM) implements a hybrid
    multi-process, multi-threaded web server. A fixed number of
    processes create threads to handle requests. Fluctuations in
    load are handled by increasing or decreasing the number of
    threads in each process.</p>

    <p>A single control process launches the number of child processes
    indicated by the <directive
    module="mpm_common">NumServers</directive> directive at server
    startup. Each child process creates threads as specified in the
    <code>StartThreads</code> directive. The individual threads then
    listen for connections and serve them when they arrive.</p>

    <p>Apache always tries to maintain a pool of <em>spare</em> or
    idle server threads, which stand ready to serve incoming
    requests. In this way, clients do not need to wait for new
    threads to be created. For each child process, Apache assesses
    the number of idle threads and creates or destroys threads to
    keep this number within the boundaries specified by
    <code>MinSpareThreads</code> and <code>MaxSpareThreads</code>.
    Since this process is very self-regulating, it is rarely
    necessary to modify these directives from their default values.
    The maximum number of clients that may be served simultaneously
    is determined by multiplying the number of server processes
    that will be created (<code>NumServers</code>) by the maximum
    number of threads created in each process
    (<code>MaxThreadsPerChild</code>).</p>

    <p>While the parent process is usually started as root under
    Unix in order to bind to port 80, the child processes and
    threads are launched by Apache as a less-privileged user. The
    <code>User</code> and <code>Group</code> directives are used to
    set the privileges of the Apache child processes. The child
    processes must be able to read all the content that will be
    served, but should have as few privileges beyond that as
    possible. In addition, unless <a
    href="../suexec.html">suexec</a> is used, these directives also
    set the privileges which will be inherited by CGI scripts.</p>

    <p><code>MaxRequestsPerChild</code> controls how frequently the
    server recycles processes by killing old ones and launching new
    ones.</p>

    <p>See also: <a href="../bind.html">Setting which addresses and
    ports Apache uses</a>.</p>

    <p>In addition it adds the extra ability to specify that
    specific processes should serve requests under different
    userids. These processes can then be associated with specific
    virtual hosts.</p>
    <!-- XXX: This desperately needs more explanation. -->
</summary>

<directivesynopsis location="mpm_common">
<name>CoreDumpDirectory</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>Group</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>PidFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>Listen</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>ListenBacklog</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>LockFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>MaxRequestsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>MaxSpareThreads</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>MaxThreadsPerChild</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>MinSpareThreads</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>NumServers</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>ScoreBoardFile</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>SendBufferSize</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>StartThreads</name>
</directivesynopsis>
<directivesynopsis location="mpm_common">
<name>User</name>
</directivesynopsis>

<directivesynopsis>
<name>AssignUserId</name>
<syntax>AssignUserID <em>user_id</em> <em>group_id</em></syntax>
<contextlist><context>virtual host</context></contextlist>

<usage>
    <p>Tie a virtual host to a specific child process. Requests addressed to
the virtual host where this directive appears will be served by the process
running with the specified user and group id.</p>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>ChildPerUserId</name>
<syntax>ChildPerUserID <em>user_id</em>
<em>group_id</em> <em>child_id</em></syntax>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>Specify a user id and group id for a specific child process. The number of
children if set by the <a href="mpm_common.html#numservers">NumServers</a>
directive. For example, the default value for <a
href="mpm_common.html#numservers">NumServers</a> is 5 and that means
children ids 1,2,3,4 and 5 are available for assigment. If a child does not
have an associated ChildPerUserID, it inherits the <a
href="mpm_common.html#user">User</a> and <a
href="mpm_common.html#group">Group</a> settings from the main server </p> 
</usage>
</directivesynopsis>

</modulesynopsis>

=== thjc/httpd-crcsyncproxy/docs/manual/mod/prefork.xml
<?xml version="1.0"?>
<!DOCTYPE modulesynopsis SYSTEM "../style/modulesynopsis.dtd">
<?xml-stylesheet type="text/xsl" href="../style/manual.xsl"?>
<modulesynopsis>

<name>prefork</name>
<description>Implements a non-threaded, pre-forking web server</description>
<status>MPM</status>
<sourcefile>prefork.c</sourcefile>
<identifier>mpm_prefork_module</identifier>

<summary>
    <p>This Multi-Processing Module (MPM) implements a
    non-threaded, pre-forking web server which handles request in a
    manner very similar to the default behavior of Apache 1.3 on
    Unix.</p>

    <p>A single control process is responsible for launching child
    processes which listen for connections and serve them when they
    arrive. Apache always tries to maintain several <em>spare</em>
    or idle server processes, which stand ready to serve incoming
    requests. In this way, clients do not need to wait for a new
    child processes to be forked before their requests can be
    served.</p>

    <p>The <directive module="mpm_common">StartServers</directive>,
    <directive module="prefork">MinSpareServers</directive>,
    <directive module="prefork">MaxSpareServers</directive>, and
    <directive module="mpm_common">MaxClients</directive> regulate how
    the parent process creates children to serve requests. In general,
    Apache is very self-regulating, so most sites do not need to
    adjust these directives from their default values. Sites which
    need to serve more than 256 simultaneous requests may need to
    increase <directive module="mpm_common">MaxClients</directive>,
    while sites with limited memory may need to decrease <directive
    module="mpm_common">MaxClients</directive> to keep the server from
    thrashing (swapping memory to disk and back). More information
    about tuning process creation is provided in the <a
    href="../misc/perf-tuning.html">performance hints</a>
    documentation.</p>

    <p>While the parent process is usually started as root under Unix
    in order to bind to port 80, the child processes are launched by
    Apache as a less-privileged user. The <directive
    module="mpm_common">User</directive> and <directive
    module="mpm_common">Group</directive> directives are used to set
    the privileges of the Apache child processes. The child processes
    must be able to read all the content that will be served, but
    should have as few privileges beyond that as possible. In
    addition, unless <a href="../suexec.html">suexec</a> is used,
    these directives also set the privileges which will be inherited
    by CGI scripts.</p>

    <p><directive module="mpm_common">MaxRequestsPerChild</directive>
    controls how frequently the server recycles processes by killing
    old ones and launching new ones.</p>
</summary>
<seealso><a href="../bind.html">Setting which addresses and
    ports Apache uses</a></seealso>

<directivesynopsis location="mpm_common">
<name>CoreDumpDirectory</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>PidFile</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>Listen</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>ListenBacklog</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>LockFile</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>MaxRequestsPerChild</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>MaxSpareServers</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>MinSpareServers</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>ScoreBoardFile</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>SendBufferSize</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>ServerLimit</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>StartServers</name>
</directivesynopsis>

<directivesynopsis location="mpm_common">
<name>User</name>
</directivesynopsis>

<directivesynopsis>
<name>AcceptMutex</name>
<description>Method that Apache uses to serialize multiple children
accepting requests on network sockets</description>
<syntax>AcceptMutex default|<em>method</em></syntax>
<default>AcceptMutex default</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>The <directive>AcceptMutex</directive> directives sets the
    method that Apache uses to serialize multiple children accepting
    requests on network sockets. Prior to Apache 2.0, the method was
    selectable only at compile time. The optimal method to use is
    highly architecture and platform dependent. For further details,
    see the <a href="../misc/perf-tuning.html">performance tuning</a>
    documentation.</p>

    <p>If this directive is set to <code>default</code>, then the
    compile-time selected default will be used. Other possible
    methods are listed below. Note that not all methods are
    available on all platforms. If a method is specified which is
    not available, a message will be written to the error log
    listing the available methods.</p>

    <dl>
      <dt><code>flock</code></dt>

      <dd>uses the <code>flock(2)</code> system call to lock the
      file defined by the <directive module="mpm_common"
      >LockFile</directive> directive.</dd>

      <dt><code>fcntl</code></dt>

      <dd>uses the <code>fnctl(2)</code> system call to lock the
      file defined by the <directive module="mpm_common"
      >LockFile</directive> directive.</dd>

      <dt><code>sysvsem</code></dt>

      <dd>uses SySV-style semaphores to implement the mutex.</dd>

      <dt><code>pthread</code></dt>

      <dd>uses POSIX mutexes as implemented by the POSIX Threads
      (PThreads) specification.</dd>
    </dl>
</usage>
</directivesynopsis>

<directivesynopsis>
<name>MaxSpareServers</name>
<description>Maximum number of idle child server processes</description>
<syntax>MaxSpareServers <em>number</em><br /></syntax>
<default>MaxSpareServers 10</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>The <directive>MaxSpareServers</directive> directive sets the
    desired maximum number of <em>idle</em> child server processes. An
    idle process is one which is not handling a request. If there are
    more than MaxSpareServers idle, then the parent process will kill
    off the excess processes.</p>

    <p>Tuning of this parameter should only be necessary on very
    busy sites. Setting this parameter to a large number is almost
    always a bad idea.</p>
</usage>
<seealso><directive module="prefork">MinSpareServers</directive></seealso>
<seealso><directive module="mpm_common">StartServers</directive></seealso>
</directivesynopsis>

<directivesynopsis>
<name>MinSpareServers</name>
<description>Minimum number of idle child server processes</description>
<syntax>MinSpareServers <em>number</em></syntax>
<default>MinSpareServers  5</default>
<contextlist><context>server config</context></contextlist>

<usage>
    <p>The <directive>MinSpareServers</directive> directive sets the
    desired minimum number of <em>idle</em> child server processes. An
    idle process is one which is not handling a request. If there are
    fewer than MinSpareServers idle, then the parent process creates
    new children at a maximum rate of 1 per second.</p>

    <p>Tuning of this parameter should only be necessary on very
    busy sites. Setting this parameter to a large number is almost
    always a bad idea.</p>

    <p>This directive has no effect on Microsoft Windows.</p>
</usage>
<seealso><directive module="prefork">MaxSpareServers</directive></seealso>
<seealso><directive module="mpm_common">StartServers</directive></seealso>
</directivesynopsis>

</modulesynopsis>
